---
- hosts: localhost
  become: yes
  tasks:
    - name: Instalar Apache
      yum:
        name: httpd
        state: present

    - name: Iniciar y habilitar Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Crear página web de ejemplo
      copy:
        dest: /var/www/html/index.html
        content: "<h1>¡Hola desde Ansible en AWS!</h1>"
